### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by tyssen** [ovdojoey/Juiced#2]
No mention of browser support anywhere I can see. Presumably it's the same as Flexbox itself, but are there any fallbacks built in or do we have to come up with our own?

**Comment by louisnovick** [comment]
It says in the README, "It is built on the Flexible Boxes Layout spec and is supported by all modern browsers IE10+."

**Comment by tyssen** [comment]
So no info or advice on what to do to support older browsers?

**Comment by louisnovick** [comment]
You could use modernizr to detect the older browsers and create specific styles for certain elements on the page for those cases.  I'm not sure a flexbox css framework would suit your needs if you absolutely need to support older browsers like IE9 or below.
