### ISSUE TITLE
Colours (or colors) usage

### ISSUE THREAD

**Issue by notenociz** [ovdojoey/Juiced#4]
Hey, would there be a reason not to have more colours? I'd love if the colours used in http://mrmrs.cc were used here and if like in it, there'd be utility classes to allow to colour SVG elements as well.

Check it out and let me know your thoughts!

(Btw, loving this. I came from http://tachyons.io to here because Tachyons has non-heuristic class names (I.e.: .dib-SM doesn't show that it's display: inline-block; on small breakpoint, exactly.))

**Comment by ovdojoey** [comment]
Sounds like a nice idea!  More colors can surely be added.  Take a look at `/sass/_variables.scss`, and `/sass/_helpers.scss` for the spots where colors are used if you want to modify the Juiced source.  I like the colors project you listed and think it would be fairly easy for you to create a custom build with that project in it, simply change the `/sass/juiced.scss` file to import the colors css file at the top and you can have both sets of color classes.
