### ISSUE TITLE
More margin, padding and width classes

### ISSUE THREAD

**Issue by notenociz** [ovdojoey/Juiced#5]
I like how you've put a .no-margin class. But how about if I wanted to put a margin? How am I meant to do that?

Do you use the grid to do that? 

If not, would there be a possibility for classes such as .max-width-50 or .width-25?

**Comment by ovdojoey** [comment]
The grid allows for some basic padding options to provide gutters, but for custom margins you'd need to specify that in your own custom CSS.  Feel free to add in .max-width classes and I'll take a look at merging those in :+1:
